${name}${version_strip}:
	image: $image
	working_dir: $working_dir
	entrypoint: $entrypoint
	ports:
$(for num in ${ports[@]}; do echo "\t\t- $num"; done)
	volumes:
$(for num in ${volumes[@]}; do echo "\t\t- \"$num\""; done)
	environment:
$(for num in ${environment[@]}; do echo "\t\t- $num"; done)